### PR TITLE
Update archive

### PR DESCRIPTION
**Pull request by Steven-Palayew**
Updates the archive folder with most important code in model development and testing process, along with a description file. 
Some questions that should probably be addressed before we merge: 
1. I'm using the original code here I used to generate model etc, but would it be a good idea to add more comments to this code? Or just leave as is? If yes to comments, should I create two copies (ie. original, commented)? 
2. Am I including too much code/files? Too little?

### CODE REVIEW

**Comment by Steven-Palayew** [comment]
Note - I started updating this in main branch rather than this branch - I recommend you review the whole folder.

**Comment by JohnGiorgi** [comment]
Hey @Steven-Palayew what is the purpose of the archive folder? Also tagging @jvwong because I think he is more likely to have to use this than me.

> I'm using the original code here I used to generate model etc, but would it be a good idea to add more comments to this code? Or just leave as is? If yes to comments, should I create two copies (ie. original, commented)?

The rule of thumb is to comment anything that is non-obvious and not understood from the code itself. E.g. if you have a line of code that does `model = load_model(...)` don't comment this "Loads model" because that's easily understood. No, don't maintain two versions of the code ever if possible. This violates the [DRY principle](https://deviq.com/principles/dont-repeat-yourself).

> Am I including too much code/files? Too little?

You should include anything necessary to repeat what you did, including training and evaluating the model, tuning hyperparameters, etc. etc.

**Comment by Steven-Palayew** [comment]
@JohnGiorgi this is just meant as a reference, and contains the most important notebooks involved in the model training/development process. If I included literally everything involved in this process, you're talking about a number of notebooks that I don't think would be practical to go through ( ie >10). 

> You should include anything necessary to repeat what you did, including training and evaluating the model, tuning hyperparameters, etc. etc.

So basically while I think this seems overkill, I figure I need some sort of middleground between that and just not having an archive folder at all.

**Comment by JohnGiorgi** [comment]
> @JohnGiorgi this is just meant as a reference, and contains the most important notebooks involved in the model training/development process. If I included literally everything involved in this process, you're talking about a number of notebooks that I don't think would be practical to go through ( ie >10).
> 
> > You should include anything necessary to repeat what you did, including training and evaluating the model, tuning hyperparameters, etc. etc.
> 
> So basically while I think this seems overkill, I figure I need some sort of middleground between that and just not having an archive folder at all.

Just use your best judgment. As a very general rule of thumb anything needed to reproduce your results should be on GitHub, there's no argument here for omitting it. No problem if you don't want to include one-off notebooks that you used for less critical things.

**Comment by Steven-Palayew** [comment]
@JohnGiorgi a little bit confused as to what you mean by this. 

demo_model_kaggle.ipynb should be enough in and of itself to just train a model given data that has been collected, and when necessary combined correctly, along with potentially mislabeled articles identified by cleanlab. From there I also included: 

- files I used to assess model performance 
- file that uses cleanlab to identify potentially mislabeled articles, since this isn't routine or basic. 

I omitted: 
- Files that basically just did data wrangling on the somewhat messy data I was initially given 
- Files that were used for experimentation

**Comment by JohnGiorgi** [comment]
> @JohnGiorgi a little bit confused as to what you mean by this.
> 
> demo_model_kaggle.ipynb should be enough in and of itself to just train a model given data that has been collected, and when necessary combined correctly, along with potentially mislabeled articles identified by cleanlab. So I suppose this is sort of enough to reproduce my results given I also included data in Data folder? From there I also included:
> 
>     * files I used to assess model performance
> 
>     * file that uses cleanlab to identify potentially mislabeled articles, since this isn't routine or basic.
> 
> 
> I omitted:
> 
>     * Files that basically just did data wrangling on the somewhat messy data I was initially given
> 
>     * Files that were used for experimentation

You originally asked: "Am I including too much code/files? Too little?" I was simply trying to answer that question. If you already include everything needed to reproduce your trained model, then you are not including too much or too little.

**Comment by Steven-Palayew** [comment]
Right sorry if I wasn't super clear here. So just to confirm it's okay that I included enough on here just to reproduce the training and asssesment of the model featured on this repository, and I don't need to include enough code to replicate everything important I did during the term?

**Comment by JohnGiorgi** [comment]
> Right sorry if I wasn't super clear here. So just to confirm it's okay that I included enough on here just to reproduce the training and asssesment of the model featured on this repository, and I don't need to include enough code to replicate everything important I did during the term?

I don't see the argument for excluding anything -- unless it was just some throwaway script you used once. You don't have to spend a bunch of time cleaning it up or anything, just upload it to archive.

**Comment by Steven-Palayew** [comment]
@JohnGiorgi lmk if we're good to go here

**Comment by JohnGiorgi** [comment]
> @JohnGiorgi lmk if we're good to go here 

Yup will you just rename the description file to README.md so GitHub renders it?

**Comment by Steven-Palayew** [comment]
Yep done

**Comment by JohnGiorgi** [comment]
> Yep done 

Awesome, LGTM!

**Pull request merged**
