### PR TITLE
Update pyproject.toml

### PR DESCRIPTION
**Pull request by Steven-Palayew**
Restrict python versions. I believe this is the correct syntax

### CODE REVIEW

**Comment by JohnGiorgi** [comment]
LGTM, maybe just check that you can run `poetry install` with this change but otherwise lets merge!

**Comment by Steven-Palayew** [comment]
> LGTM, maybe just check that you can run `poetry install` with this change but otherwise lets merge!

Hmm seems like I need to run 'poetry update' to update lock file before checking that. So maybe take care of all that locally and then merge?

**Comment by Steven-Palayew** [comment]
> > LGTM, maybe just check that you can run `poetry install` with this change but otherwise lets merge!
> 
> Hmm seems like I need to run 'poetry update' to update lock file before checking that. So maybe take care of all that locally and then merge?

Update - this lead to error `Command '['C:\\Program Files\\Git\\cmd\\git.exe', 'clone', '--recurse-submodules', '--', 'https://github@github.com/amaiya/stellargraph', 'C:\\Users\\spala\\AppData\\Local\\Temp\\pypoetry-git-stellargraphisf3hmll']' returned non-zero exit status 128.`, Maybe we should try restricting to newer versions of ktrain? @JohnGiorgi

**Comment by JohnGiorgi** [comment]
@Steven-Palayew This should be closed when #5 is merged.

**Pull request closed without merging**
