### PR TITLE
Update Test File

### PR DESCRIPTION
**Pull request by Steven-Palayew**
Update test file to be more complete, and to verify that code in Quickstart works.

### CODE REVIEW

**Review by JohnGiorgi — CHANGES_REQUESTED** [review]
Hi @Steven-Palayew, looks good, I have a couple of suggestions:

- I would move everything currently under `if __name__ == "__main__":` to a new function above. It is common to call this `main`, which cant then be called under `if __name__ == "__main__":` simply like `main()`. This is more modular, canonical and easier to update if we decide to extend it (e.g. by adding command-line arguments). You can see a sort of template here: https://typer.tiangolo.com/tutorial/first-steps/.
- I would rename the file. Typically, files named `test*.py` denote files that contain unit tests. Popular tools like [pytest](https://docs.pytest.org/en/7.1.x/getting-started.html) will actually assume this and automatically run these files. A canonical thing to name a file like this is simply `main.py` (are you noticing a pattern haha?)

**Comment by Steven-Palayew** [comment]
@JohnGiorgi great suggestions thanks. I was thinking about doing point 1 that way but ended up going with what I have since I didn't think we were going to expand on this file. But if it's best practice to do things the way you suggested even for a file like this it seems like a no brainer. Regarding point 2, making this a proper unit test sounds interesting and I'd definitely like to take a stab at that. Also didn't know naming a file test.py could cause unexpected behaviour like that, that's great to know thanks!

Right now I'm working on running model on the test set I made and the test set Jeff recently sent over, but will make the changes you suggested when I'm done that.

**Comment by JohnGiorgi** [comment]
@Steven-Palayew Sounds good! If you like, you could just address point 1 in this PR and merge (should be very quick). Then we can take about making this a proper unit test in another issue/PR.

**Comment by Steven-Palayew** [comment]
@JohnGiorgi done. I left name as test.py in anticipation of making this a proper unit test, but lmk if you'd like me to change it to main.py .

**Review by JohnGiorgi — APPROVED** [review]

**Comment by JohnGiorgi** [comment]
LGTM 👍

**Pull request merged**
