### PR TITLE
Update [SEP] token method

### PR DESCRIPTION
**Pull request by Steven-Palayew**

### CODE REVIEW

**Review by JohnGiorgi — CHANGES_REQUESTED** [review]
Looks good to me as long is this is everywhere `"[SEP]"` is used in the repo. Wouldn't it also be in the tutorial notebook?

**Comment by Steven-Palayew** [comment]
@JohnGiorgi yeah I already made this change to Kaggle notebook (there's a built in method to just commit when you save). For next time I'll look into how to do a PR with notebook if you want.

**Review by JohnGiorgi — APPROVED** [review]
LGTM then, remember to link this to the issue though using [closing keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword), e.g. closes #8.

**Comment by Steven-Palayew** [comment]
Yep sounds good thanks. Did that for the last issue (10 I think?)

**Pull request merged**
